# Generated by Django 5.1.4 on 2025-01-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyp_aut_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezerwacje',
            old_name='car',
            new_name='Auta',
        ),
    ]
